config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  namespace :api, defaults: {format: 'json'}  do
    # /api/ ... Api::
    namespace :v1 do
      resources :bumblebees
    end
  end
  root                      'static_pages#home'
  post 'help' => 'static_pages#help'
  get     'help'        =>  'static_pages#help'
  get     'about'       =>  'static_pages#about'
  get     'contact'     =>  'static_pages#contact'
  get     'signup'      =>  'users#new'
  get     'login'       =>  'sessions#new'
  post    'login'       =>  'sessions#create'
  delete  'logout'      =>  'sessions#destroy'
  get     'unconfirmed' =>  'bumblebees#unconfirmed'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  # resources :bumblebees,          only: [:create, :destroy, :edit, :update]
  resources :bumblebees
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  protect_from_forgery with: :exception
  before_action :detect_browser


  require 'rest-client'
  API_BASE_URL = "http://212.235.208.133:9001/classify"
  
  def classify
#    RestClient.post('http://212.235.208.133:9001/classify', :audio => File.new('owl_call.wav'))
    # @response = RestClient.post('http://212.235.208.133:9001/classify', :audio => File.new('owl_call.wav'))
    puts "test"
  end

  def home
    if logged_in? 
      @bumblebee = current_user.bumblebees.build 
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end

  private
    def detect_browser
      case request.user_agent
        when /iPad/i
          request.variant = :tablet
          render layout: "mobile_layout"
        when /iPhone/i
          request.variant = :phone
          render layout: "mobile_layout"
        when /Android/i && /mobile/i
          request.variant = :phone
          render layout: "mobile_layout"
        when /Android/i
          request.variant = :tablet
          render layout: "mobile_layout"
        when /Windows Phone/i
          request.variant = :phone
          render layout: "mobile_layout"
        else
          request.variant = :desktop
      end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>Sample App</h1>
<p>
This it the home page for the static_pages tutorial in progress. You can find it <a href="./about">here</>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
    Here will be some contact infomartion as soon as we fix links like <a href="#">this</a>one.
    </p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Sample App</h1>
<p>
This it the home page for the BumbleeBee app in progress. You can find it <a href="./help">here</>
</p>
<a href="#">test</a>

<%= form_tag 'http://212.235.208.133:9001/classify', id: 'myForm', multipart: true, target: 'myFrame', remote: true do %>
  <span class="btn btn-primary btn-large btn-block btn-file">Select recording
  <%= file_field_tag 'file', accept: 'audio/wav' %>
  </span>
  <%= submit_tag 'Classify', id: "submit-button", class: "btn btn-primary btn-large btn-block" %>
<% end %>

<div>
    <iframe name=myFrame id='iframe2' frameborder="0" style="overflow: hidden; height: 100%;
        width: 100%; position: absolute;" height="100%" width="100%"></iframe>
</div>

app/views/static_pages/home.html+phone.erb
<div class="row">
  <h1>Recognize bumblebee</h1>
  <p id="mob-p">1) Tap on a button 'Select recording' to load sound (file type must be <b>wav</b>) from your device</p> 
  <p id="mob-p">2) Tap on a button 'results' to get results about bumblebee</p>
  <p id="mob-p"><em id="mob-em">Note: you must be connected to the internet for results to work</em></p>

  <%= form_tag 'http://212.235.208.133:9001/classify', id: 'myForm', multipart: true, target: 'myFrame', remote: true do %>
    <span class="btn btn-primary btn-xlarge btn-block btn-file">Select recording
    <%= file_field_tag 'file', accept: 'audio/wav' %>
    </span>
    <%= submit_tag 'Classify', id: "submit-button", class: "btn btn-primary btn-xlarge btn-block" %>
  <% end %>

  <div>
      <iframe name=myFrame id='iframe-mobi' frameborder="0" style="overflow: hidden; height: 100%;
          width: 100%; position: absolute;" height="100%" width="100%"></iframe>
  </div>

</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="bumblebee_form">
        <%= render 'shared/bumblebee_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Bumblebee Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Bumblebee App</h1>
    This it the home page for the Bunblebee app in progress. You can find it <%= link_to "here", '#' %>.

    <h2>
      This is the home page for the <a href=".">BunbleBee app</a>
    </h1>


    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>

  <%= link_to image_tag("rails.png", alt: "Rails logo"), 
              'http://rubyonrails.org/' %>
<% end %>