config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  namespace :api, defaults: {format: 'json'}  do
    # /api/ ... Api::
    namespace :v1 do
      resources :bumblebees
    end
  end
  root                      'static_pages#home'
  post 'help' => 'static_pages#help'
  get     'help'        =>  'static_pages#help'
  get     'about'       =>  'static_pages#about'
  get     'contact'     =>  'static_pages#contact'
  get     'signup'      =>  'users#new'
  get     'login'       =>  'sessions#new'
  post    'login'       =>  'sessions#create'
  delete  'logout'      =>  'sessions#destroy'
  get     'unconfirmed' =>  'bumblebees#unconfirmed'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  # resources :bumblebees,          only: [:create, :destroy, :edit, :update]
  resources :bumblebees
end

app/models/bumblebee.rb
class Bumblebee < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc)  }
  mount_uploader :picture, PictureUploader
  mount_uploader :sound, SoundUploader
  validates :user_id,     presence: true
  #validates :description, presence: true
  # validates :sound,       presence: true
  validate  :picture_size, :sound_size

  private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end

    def sound_size
      if sound.size > 5.megabytes
        errors.add(:sound, "Should be less than 5MB")
      end
    end
end

app/controllers/api/v1/bumblebees_controller.rb
module Api
  module V1
    class BumblebeesController < ApplicationController
      before_action :doorkeeper_authorize! # Require access token for all actions
      respond_to :json

      def index
        respond_with current_user.bumblebees
        # respond_with Bumblebee.all.where(approved: true)
      end

      def show
        respond_with Bumblebee.find(params[:id])
      end

      def create
        respond_with Bumblebee.create(params[:bumblebee])
      end

      def update
        respond_with Bumblebee.update(params[:id], params[:bumblebee])
      end

      def destroy
        respond_with Bumblebee.destroy(params[:id])
      end

      private 

        def current_user
          @current_user ||= User.find(doorkeeper_token.resource_owner_id)
        end
    end
  end
end

app/controllers/bumblebees_controller.rb
class BumblebeesController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: [:destroy, :edit]

  def create
    @bumblebee = current_user.bumblebees.build(bumblebee_params)
    if @bumblebee.save
      flash[:success] = "Bumblebee created!"
      redirect_to root_url
    else
      # Failed submission currently break - we suppress the feed entirely by 
      # assigning it an empty array
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @bumblebee.destroy
    flash[:success] = "Bumblebee deleted"
    redirect_to request.referrer || root_url
  end

  def edit
    @bumblebee = if current_user.admin?
      Bumblebee.find(params[:id])
    else
      current_user.bumblebees.find_by(id: params[:id])
    end
  end

  def update
    @bumblebee = if current_user.admin?
      Bumblebee.find(params[:id])
    else
      current_user.bumblebees.find_by(id: params[:id])
    end
    if @bumblebee.update_attributes(bumblebee_params)
      # Handle a successful update.
      flash[:success] = "Bumblebee updated"
      redirect_to root_url 
    else 
      flash[:warning] = "Bumblebee not updated"
    end
  end

  def unconfirmed
    if logged_in? && user_admin?
      # @bumblebee = current_user.bumblebees.build 
      # @feed_items = current_user.feed.paginate(page: params[:page])
      @feed_items = Bumblebee.all.where(approved: nil).paginate(page: params[:page])
    end
  end

  def index
    @feed_items = Bumblebee.all.where(approved: true).paginate(page: params[:page])
    @bumblebees = Bumblebee.all.where(approved: true)
    respond_to do |format|
      format.html
      format.json { render json: @bumblebees.as_json(only: [:id, :species, :gender_type, :sound, :image]) }
    end
  end

  def show
    @bumblebee = Bumblebee.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @bumblebee.as_json(only: [:id, :species, :gender_type, :sound]) }
    end
  end
  private

    def bumblebee_params
      params.require(:bumblebee).permit(:description, :picture, :species,
                                        :gender_type, :sound, :approved)

    end

    def correct_user
      @bumblebee = if current_user.admin?
        Bumblebee.find(params[:id])
      else
        current_user.bumblebees.find_by(id: params[:id])
      end
      redirect_to root_url if @bumblebee.nil?
    end
end

app/helpers/bumblebees_helper.rb
module BumblebeesHelper
end

app/views/bumblebees/_bumblebee.html.erb
<li id="bumblebee-<%= bumblebee.id %>">
  <%= link_to gravatar_for(bumblebee.user, size: 50), bumblebee.user %>
  <span class="user"><%= link_to bumblebee.user.name, bumblebee.user %></span>
  <span class="description">
    <%= bumblebee.description %>
    <% if bumblebee.species != "" %>
      <em>Species: </em><%= bumblebee.species %>
    <% end %>
    <% if bumblebee.gender_type == 0 %>
      -worker-
    <% elsif bumblebee.gender_type == 1 %>
      -queen-
    <% else %>
      -no gender/type-
    <% end %>
    <%= image_tag bumblebee.picture.url() if bumblebee.picture? %>
    <a href="<%= bumblebee.sound.url %>">Play sound</a>
  </span>
  <span class="timestamp">
    Added <%= time_ago_in_words(bumblebee.created_at) %> ago.
    <% if current_user?(bumblebee.user) || user_admin? %>
      <%= link_to "delete",  bumblebee, method: :delete,
                                       data: { confirm: "You sure?" } %>
                                     |
      <%= link_to "edit",    edit_bumblebee_path(bumblebee) %>
      <% if user_admin? %>
        <%= form_for(bumblebee) do |f| %>
          <%= f.hidden_field :approved, :value => "true" %>
          <%= f.submit "Confirm", class: "btn btn-prinary" %>
        <% end %>
      <% end %>
    <% end %>
  </span>
</li>

app/views/bumblebees/edit.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="bumblebee_form">
        <%= render 'shared/bumblebee_form_edit' %>
      </section>
    </aside>
  </div>
<% end %>

app/views/bumblebees/index.html.erb
<h3>All confirmed bumblebees</h3>
<div class="bumblebees-index">
    <% @bumblebees.reorder('updated_at desc').each do |b| %>
      <% gender = "" %>
      <% gender = "worker" if b.gender_type ==  0 %>
      <% gender = "queen" if b.gender_type ==  1 %>
      <% gender = "no_gender" if b.gender_type == 2 %>
      <ul>
        <li>id: <%= link_to b.id, b %></li>
        <li>Species: <%= b.species %></li>
        <li>Type: <%= gender %></li>
        <li><%= image_tag b.picture.url() %></li>
        <li id="bumblebee-middle">Description: <%= b.description %></li>
        <li id="bumblebee-right">Sound: <a href="<%= b.sound.url() %>">Play</a></li>
      </ul>
    <% end %>
</div>

app/views/bumblebees/show.html.erb
<h3>Single bumblebee</h3>
<div class="bumblebee-index">
  <% gender = "" %>
  <% gender = "worker" if @bumblebee.gender_type ==  0 %>
  <% gender = "queen" if @bumblebee.gender_type ==  1 %>
  <% gender = "no_gender" if @bumblebee.gender_type == 2 %>
  <ul>
    <li>id: <%= @bumblebee.id %></li>
    <li>Species: <%= @bumblebee.species %></li>
    <li>Type: <%= gender %></li>
    <li><%= image_tag @bumblebee.picture.url() %></li>
    <li id="bumblebee-middle">Description: <%= @bumblebee.description %></li>
    <li id="bumblebee-right">Sound: <a href="<%= @bumblebee.sound.url() %>">Play</a></li>
  </ul>
</div>

app/views/bumblebees/unconfirmed.html.erb
<div class="row">
  <div class="col-md-8">
    <h3>Unconfirmed bumblebees</h3>
  </div>
</div>

<% if logged_in? && user_admin? %>
  <div class="row">
    <div class="col-md-8">
      <%= render 'shared/feed' %>
    </div>
  </div>
<% end %>